# Root App: app-of-apps pattern for all child applications.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Heaven229-c/w10-xbrain.git
    path: cloud/w10/project-02-secure-operate-gitops-lab/argocd/apps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




