apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
  namespace: demo
  labels:
    app: api
    owner: platform-team
    env: w10
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        owner: platform-team
        env: w10
    spec:
      containers:
        - name: api
          image: ghcr.io/heaven229-c/w10-api:9a82f97
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: VERSION
              value: "v9a82f97"
            - name: ERROR_RATE
              value: "0"
            - name: DB_PASSWORD_FILE
              value: /var/run/secrets/w10-db/password
          volumeMounts:
            - name: db-secret
              mountPath: /var/run/secrets/w10-db
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: db-secret
          secret:
            secretName: db-secret
            optional: true
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 1
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 50
        - pause:
            duration: 2m
        - setWeight: 100



