# ArgoCD App: custom Gatekeeper ConstraintTemplates for Lab 03.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-custom-templates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/Heaven229-c/w10-xbrain.git
    path: cloud/w10/project-02-secure-operate-gitops-lab/gatekeeper/custom/templates
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
